[NUC972][CHG]修改脚本打印log方式，将log存入syslog.

diff --git a/board/nuvoton/rootfs-yytd/etc/init.d/S30mount b/board/nuvoton/rootfs-yytd/etc/init.d/S30mount
--- a/board/nuvoton/rootfs-yytd/etc/init.d/S30mount
+++ b/board/nuvoton/rootfs-yytd/etc/init.d/S30mount
@@ -3,24 +3,25 @@
 # Start mount....
 #
 
+TAG="MOUNT"
 case "$1" in
   start)
 	if [ -e /dev/mmcblk0p1 ]; then 
-		printf "Starting mount SD card..."
+		logger -t ${TAG} -s "Starting mount SD card..."
 		/bin/mount -t vfat -o uid=1000,gid=1000 /dev/mmcblk0p1 /media/sd
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 	fi
 	
 	if [ -e /dev/mtdblock0 ]; then
-		printf "Starting mount yy..."
+		logger -t ${TAG} -s "Starting mount yy..."
 		/bin/mount -t yaffs2 /dev/mtdblock0 /yy
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 	fi
 
 	if [ -e /dev/mtdblock1 ];then
-		printf "Starting mount userdata..."
+		logger -t ${TAG} -s "Starting mount userdata..."
 		/bin/mount -t yaffs2 /dev/mtdblock1 /userdata 
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 	fi
 	;;
   stop)
diff --git a/board/nuvoton/rootfs-yytd/etc/init.d/S60pureftpd b/board/nuvoton/rootfs-yytd/etc/init.d/S60pureftpd
--- a/board/nuvoton/rootfs-yytd/etc/init.d/S60pureftpd
+++ b/board/nuvoton/rootfs-yytd/etc/init.d/S60pureftpd
@@ -1,12 +1,13 @@
 #!/bin/sh
 
+TAG="FTP"
 ARGS="-0 -1 -4 -A -B -C 8 -c 7 -D -E -H -I 10 -j -l puredb:/etc/pureftpd.pdb -s -z -Z"
 start() {
     #pure-ftpd -l puredb:/etc/pureftpd.pdb &
-    printf "Starting pureftpd: "
+    logger -t ${TAG} -s "Starting pureftpd: "
     start-stop-daemon -S -q -p /var/run/pureftpd.pid \
     --exec /usr/sbin/pure-ftpd -- $ARGS
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    [ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 }
 
 case "$1" in
@@ -14,9 +15,9 @@ case "$1" in
         start
         ;;
     stop)
-	printf "Stopping pureftpd: "
+	logger -t ${TAG} -s "Stopping pureftpd: "
 	start-stop-daemon -K -q -p /var/run/pureftpd.pid
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 	;;
     *)
         echo "Usage: /etc/init.d/S50pureftpd {start|stop}"
diff --git a/board/nuvoton/rootfs-yytd/etc/init.d/S99APPstart b/board/nuvoton/rootfs-yytd/etc/init.d/S99APPstart
--- a/board/nuvoton/rootfs-yytd/etc/init.d/S99APPstart
+++ b/board/nuvoton/rootfs-yytd/etc/init.d/S99APPstart
@@ -3,21 +3,21 @@
 # Start YYTD start.sh....
 #
 
-
+TAG="YYTD"
 first_start(){
 	if [ -e /dev/mtdblock5 ];then
-		printf "Starting mount app mtdblock..."
+		logger -t ${TAG} -s "Starting mount app mtdblock..."
 		mount -t jffs2 /dev/mtdblock5 /tmp/ 
 		if [ $? = 0 ];then 
-			echo "OK" 
+			logger -t ${TAG} -s "OK" 
 		else
-			echo "FAIL" && exit 1
+			logger -t ${TAG} -s "FAIL" && exit 1
 		fi
         fi
 	
-	printf "Uncompress app.tar.gz to yy folder"
+	logger -t ${TAG} -s "Uncompress app.tar.gz to yy folder"
 	tar xf /tmp/app.tar.gz -C /yy/
-	[ $? = 0 ] && echo "OK" || echo "FAIL" 
+	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL" 
 	
 	umount /tmp/
 	/yy/app/start.sh &
@@ -27,9 +27,9 @@ first_start(){
 case "$1" in
   start)
         if [ -e /yy/app/start.sh ]; then
-                printf "Starting YYTD app..."
+                logger -t ${TAG} -s "Starting YYTD app..."
                 /yy/app/start.sh &
-                [ $? = 0 ] && echo "OK" || echo "FAIL"
+                [ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 	else 
 		first_start
 		
diff --git a/package/dropbear/S50dropbear b/package/dropbear/S50dropbear
--- a/package/dropbear/S50dropbear
+++ b/package/dropbear/S50dropbear
@@ -20,23 +20,23 @@ start() {
 		if rm -f /etc/dropbear >/dev/null 2>&1; then
 			mkdir -p /etc/dropbear
 		else
-			echo "No persistent location to store SSH host keys. New keys will be"
-			echo "generated at each boot. Are you sure this is what you want to do?"
+			logger -t ${TAG} -s "No persistent location to store SSH host keys. New keys will be"
+			logger -t ${TAG} -s "generated at each boot. Are you sure this is what you want to do?"
 			mkdir -p "$(readlink /etc/dropbear)"
 		fi
 	fi
 
-	printf "Starting dropbear sshd: "
+	logger -t ${TAG} -s "Starting dropbear sshd: "
 	umask 077
 
 	start-stop-daemon -S -q -p /var/run/dropbear.pid \
 		--exec /usr/sbin/dropbear -- $DROPBEAR_ARGS
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 }
 stop() {
-	printf "Stopping dropbear sshd: "
+	logger -t ${TAG} -s "Stopping dropbear sshd: "
 	start-stop-daemon -K -q -p /var/run/dropbear.pid
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
 }
 restart() {
 	stop
